version: '3'
services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - ./frontend:/usr/src/app
    ports:
      - 3000:3000
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - ./backend:/usr/src/app
    ports:
      - 3001:3001
    environment:
      - DATABASE_HOST=db
  db:
    image: mysql:latest
    volumes:
      - dbdata:/var/lib/mysql
      - ./mysql/my.cnf:/etc/mysql/my.cnf
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=my-secret-pw
      - MYSQL_DATABASE=farma-commerce
      - MYSQL_USER=farma-commerce
      - MYSQL_PASSWORD=farma-commerce-password
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./frontend/build:/usr/share/nginx/html
    ports:
      - 80:80
    depends_on:
      - frontend
      - backend
volumes:
  dbdata:

networks:
  farma-commerce_net:

